# Generated by Django 5.2.7 on 2025-10-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_inter_to_char_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
