# Generated by Django 5.2.7 on 2025-10-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_user_to_customer_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Cancel Order')]},
        ),
    ]
